name: Test

on:
  [check_run]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: hello world
      uses: actions/hello-world-javascript-action@main
      with:
       who-to-greet: 'Mona the Octocat'